# Maintainer: Abner G Jacobsen
# Update: 2023-06-26

#& type: 3
#& title: Supabase
#& description: Supabase makes it easy to use Postgres.
#& note: Website: <a href='https://supabase.com/' target='_blank' rel='noopener'>Supabase</a>
#& categories: SelfHosted, Daschat
#& platform: linux
#& logo: https://supabase.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsupabase-logo-wordmark--dark.53d797e9.png&w=128&q=75

#% SERVICE: Name of the service (No spaces or points) [supabase]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service link (Example: supabase.ca1.paas.aumo.live)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
# DB_USER: Database user (No spaces or points) [wordpress]
#% DB_PASSWORD: Password for database user
# DB_ROOT: Password for database root

# Work with Portainer
version: "2"

services:
  # Database
  supabase-db:
    container_name: $SERVICE-db
    image: supabase/postgres:14.1.0
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - $DATA_LOCATION/$SERVICE/db:/var/lib/postgresql/data
      - $DATA_LOCATION/$SERVICE/db:/docker-entrypoint-initdb.d
    restart: always
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater

networks:
  default:
    external:
      name: $NETWORK